### ISSUE TITLE
Problem generating 404MHz. The example with 80Mhz works. Reference is 25MHz.

### ISSUE THREAD

**Issue by mike6000** [dfannin/adf4351#3]
I have a problem generating 404MHz out with the code below. If I modify the code below to set frequency to 80MHz with vfo.setf(80000000UL) it works fine as seen on the oscilloscope. There is a sine out at 80Mhz. 

If I try to set it to 404MHz with  vfo.setf(404000000UL) I don't get 404MHz out. 

The reference is 25MHz. 

Is there something with some dividers I have set wrong since this is a higher frequency or is there a bug in the library? I have used your example code as a basis but simplified it a bit (see below). Can you say what is wrong?

```

#include <Arduino.h>
#include "adf4351.h"

#define SWVERSION "1.0"

#define PIN_SS 9  ///< SPI slave select pin, default value

ADF4351  vfo(PIN_SS, SPI_MODE0, 1000000UL , MSBFIRST) ;


void setup()
{
  delay(5000);
  Serial.begin(9600) ;
  Serial.print("Hello adf4351 demo v") ;
  Serial.println(SWVERSION) ;
  Wire.begin() ;
  /*!
     setup the chip (for a 10 mhz ref freq) EDIT I did use 25 MHz as reference input, not 10 MHz
     most of these are defaults
  */
  vfo.pwrlevel = 0 ; ///< sets to -4 dBm output
  vfo.RD2refdouble = 0 ; ///< ref doubler off
  vfo.RD1Rdiv2 = 0 ;   ///< ref divider off
  vfo.ClkDiv = 150 ;
  vfo.BandSelClock = 80 ;
  vfo.RCounter = 1 ;  ///< R counter to 1 (no division)
  vfo.ChanStep = steps[2] ;  ///< set to 10 kHz steps


  if ( vfo.setrf(25000000UL) ==  0 )
    Serial.println("ref freq set to 25 Mhz -- modded") ;
    else
         Serial.println("ref freq set error") ;
     vfo.init() ;
     vfo.enable() ;
}

void loop()
{
  delay(1000);
 
  // ERROR! Doesn't generate 404MHz out.  
  // However if I edit this to 80MHz it works and the freq out is correct.
  Serial.println("setf() to 404 MHz instead of 80MHz") ;

  if ( vfo.setf(404000000UL) == 0 ) {
    Serial.print("setf() success freq:") ;
    Serial.println(vfo.cfreq) ;
  } else {
    Serial.println("setf() error") ;
  }
}
 
```

**Comment by dfannin** [comment]
A couple of issues.  Your reference frequency settings for 25 Mhz should be set to:
```
 vfo.RD2refdouble = 1 ; ///< ref doubler on
 vfo.RCounter = 10 ;  ///< R counter to 10 
```
so your Fpfd = 25 mhz * [ ( 1 + 1) / (10* (1+0)) ] = 5 Mhz. 

You may have to change your step size as well ; try a step size of steps[4] = 500 kHz. 

Not every frequency is available at every step size ; See the datasheet for a discussion of the PLL formula for calculating frequencies.
