### ISSUE TITLE
the relationship between real REF input and the number I set in the cades

### ISSUE THREAD

**Issue by Emrys999** [dfannin/adf4351#4]
hi! I want to know that the relationship between the real REF input and the rf I set in the code.
thank u!!!!

**Comment by dfannin** [comment]
The setrf(ref frequency) should be set to the REF frequency, in Hz.
so if you use a 10 Mhz reference frequency, then set this to 10000000UL (unsigned long). 

sets the reference frequency to 10 Mhz
 ` if ( vfo.setrf(10000000UL) ==  0 )`

sets the reference frequency
       sets the incoming reference frequency to the ADF4351 chip,
       based on your OXCO or other freqeuncy reference source value.
       Checks for min and max settings
       @param f reference frequency
       @return success (True or False)

    int setrf(uint32_t f) ;  // set reference freq`
