### ISSUE TITLE
Prescaler setting

### ISSUE THREAD

**Issue by tctsui** [dfannin/adf4351#6]
Hi, I am wondering if the criteria for choosing the value of prescaler should be "if( freq > (3600000000UL/outdiv) )" instead. 

https://github.com/dfannin/adf4351/blob/0227d800674d635a3d18b497094fda4ec9f65f16/src/adf4351.cpp#L137

**Comment by restelli** [comment]
I confirm that the line:

**Comment by restelli** [comment]
I confirm that line 137 results in the incorrect selection of the prescaler and occasional instability of the PLL resulting in a partially locked status. The solution proposed by @tctsui works.

**Comment by dfannin** [comment]
updated source based on  tctsui's suggestion. I won't be able to test this for a couple of months, but it looked reasonable. thank you @tctsui @restelli.

**Comment by dfannin** [comment]
closing.

**Comment by dfannin** [comment]
closing.
